// Code generated by MockGen. DO NOT EDIT.
// Source: avatar.go
//
// Generated by this command:
//
//	mockgen -source=avatar.go -destination=mocks/mock_avatar.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockscanner is a mock of scanner interface.
type Mockscanner struct {
	ctrl     *gomock.Controller
	recorder *MockscannerMockRecorder
	isgomock struct{}
}

// MockscannerMockRecorder is the mock recorder for Mockscanner.
type MockscannerMockRecorder struct {
	mock *Mockscanner
}

// NewMockscanner creates a new mock instance.
func NewMockscanner(ctrl *gomock.Controller) *Mockscanner {
	mock := &Mockscanner{ctrl: ctrl}
	mock.recorder = &MockscannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockscanner) EXPECT() *MockscannerMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *Mockscanner) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockscannerMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*Mockscanner)(nil).Scan), dest...)
}
