// Code generated by MockGen. DO NOT EDIT.
// Source: common.go
//
// Generated by this command:
//
//	mockgen -source=common.go -destination=mocks/mock_common.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSQLStorageInterface is a mock of SQLStorageInterface interface.
type MockSQLStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSQLStorageInterfaceMockRecorder
	isgomock struct{}
}

// MockSQLStorageInterfaceMockRecorder is the mock recorder for MockSQLStorageInterface.
type MockSQLStorageInterfaceMockRecorder struct {
	mock *MockSQLStorageInterface
}

// NewMockSQLStorageInterface creates a new mock instance.
func NewMockSQLStorageInterface(ctrl *gomock.Controller) *MockSQLStorageInterface {
	mock := &MockSQLStorageInterface{ctrl: ctrl}
	mock.recorder = &MockSQLStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLStorageInterface) EXPECT() *MockSQLStorageInterfaceMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockSQLStorageInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSQLStorageInterfaceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSQLStorageInterface)(nil).Ping), ctx)
}
