[SERVICE]
    Flush        1
    Log_Level    info
    Daemon       off

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*-json.log
    Parser            docker
    Tag               docker.*
    Refresh_Interval  5
    Skip_Long_Lines   On
    DB                /var/log/flb_state.db

[FILTER]
    Name              grep
    Match             docker.*
    Exclude           log gophprofile-opensearch-dashboards

[OUTPUT]
    Name                opensearch
    Match               docker.*
    Host                opensearch
    Port                9200
    Index               gophprofile-logs
    Suppress_Type_Name  On

[OUTPUT]
    Name            loki
    Match           docker.*
    Host            loki
    Port            3100
    Labels          job=fluent-bit
    Line_Format     json
    Retry_Limit     5
    Suppress_Type_Name  On
