[SERVICE]
    Flush        1
    Log_Level    info
    Daemon       off

[INPUT]
    Name              docker
    path.containers   /var/lib/docker/containers/
    Tag               gophprofile.*
    interval_sec      5
    Include           gophprofile
    Exclude           gophprofile-opensearch-dashboards

[OUTPUT]
    Name            opensearch
    Match           gophprofile.*
    Host            opensearch
    Port            9200
    Index           gophprofile-logs
    Type            _doc
