{{- if .Values.hpa.server.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gophprofile.name" . }}-server
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    component: server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gophprofile.name" . }}-server
  minReplicas: {{ .Values.hpa.server.minReplicas }}
  maxReplicas: {{ .Values.hpa.server.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.server.targetCPUUtilizationPercentage }}
---
{{- end }}
{{- if .Values.hpa.worker.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gophprofile.name" . }}-worker
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gophprofile.name" . }}-worker
  minReplicas: {{ .Values.hpa.worker.minReplicas }}
  maxReplicas: {{ .Values.hpa.worker.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.worker.targetCPUUtilizationPercentage }}
{{- end }}
