apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gophprofile.name" . }}-otel-collector
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      otlp/jaeger:
        endpoint: "jaeger-collector:4317"
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gophprofile.name" . }}-otel-collector
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    component: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "gophprofile.name" . }}-otel-collector
  template:
    metadata:
      labels:
        app: {{ include "gophprofile.name" . }}-otel-collector
        component: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.102.1
          args: ["--config=/etc/otel/config.yaml"]
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
            - name: metrics
              containerPort: 8889
          volumeMounts:
            - name: config
              mountPath: /etc/otel
      volumes:
        - name: config
          configMap:
            name: {{ include "gophprofile.name" . }}-otel-collector
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app: {{ include "gophprofile.name" . }}-otel-collector
spec:
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: metrics
      port: 8889
      targetPort: metrics
  selector:
    app: {{ include "gophprofile.name" . }}-otel-collector
