apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.name" . }}-secret
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_DSN: "postgres://gophprofile:secret@gophprofile-postgresql:5432/gophprofile?sslmode=disable"
  S3_ACCESS_KEY: "gk_server_access_key"
  S3_SECRET_KEY: "G0phK33p3rS3rv3r!"
