apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.name" . }}-secret
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_DSN: "postgres://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}?sslmode=disable"
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | quote }}
