apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: OpenSearch
    type: elasticsearch
    access: proxy
    url: http://opensearch:9200
    database: "gophprofile-logs*"
    jsonData:
      esVersion: "8.0.0"
      timeField: "time"
      logMessageField: "log"
      logLevelField: "stream"
      maxConcurrentShardRequests: 5
    secureJsonData:
      basicAuthUser: admin
      basicAuthPassword: admin
    editable: false
