// Code generated by MockGen. DO NOT EDIT.
// Source: avatar_service.go
//
// Generated by this command:
//
//	mockgen -source=avatar_service.go -destination=mocks/mock_avatar_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	models "github.com/KalessinD/gophprofile/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarRepository is a mock of AvatarRepository interface.
type MockAvatarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepositoryMockRecorder
	isgomock struct{}
}

// MockAvatarRepositoryMockRecorder is the mock recorder for MockAvatarRepository.
type MockAvatarRepositoryMockRecorder struct {
	mock *MockAvatarRepository
}

// NewMockAvatarRepository creates a new mock instance.
func NewMockAvatarRepository(ctrl *gomock.Controller) *MockAvatarRepository {
	mock := &MockAvatarRepository{ctrl: ctrl}
	mock.recorder = &MockAvatarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepository) EXPECT() *MockAvatarRepositoryMockRecorder {
	return m.recorder
}

// CreateAvatar mocks base method.
func (m *MockAvatarRepository) CreateAvatar(ctx context.Context, avatar *models.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvatar", ctx, avatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAvatar indicates an expected call of CreateAvatar.
func (mr *MockAvatarRepositoryMockRecorder) CreateAvatar(ctx, avatar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvatar", reflect.TypeOf((*MockAvatarRepository)(nil).CreateAvatar), ctx, avatar)
}

// GetAvatarByID mocks base method.
func (m *MockAvatarRepository) GetAvatarByID(ctx context.Context, avatarID string) (*models.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarByID", ctx, avatarID)
	ret0, _ := ret[0].(*models.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarByID indicates an expected call of GetAvatarByID.
func (mr *MockAvatarRepositoryMockRecorder) GetAvatarByID(ctx, avatarID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarByID", reflect.TypeOf((*MockAvatarRepository)(nil).GetAvatarByID), ctx, avatarID)
}

// GetAvatarsByUserID mocks base method.
func (m *MockAvatarRepository) GetAvatarsByUserID(ctx context.Context, userID string) ([]*models.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*models.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarsByUserID indicates an expected call of GetAvatarsByUserID.
func (mr *MockAvatarRepositoryMockRecorder) GetAvatarsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarsByUserID", reflect.TypeOf((*MockAvatarRepository)(nil).GetAvatarsByUserID), ctx, userID)
}

// HardDeleteAvatar mocks base method.
func (m *MockAvatarRepository) HardDeleteAvatar(ctx context.Context, avatarID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDeleteAvatar", ctx, avatarID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDeleteAvatar indicates an expected call of HardDeleteAvatar.
func (mr *MockAvatarRepositoryMockRecorder) HardDeleteAvatar(ctx, avatarID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDeleteAvatar", reflect.TypeOf((*MockAvatarRepository)(nil).HardDeleteAvatar), ctx, avatarID)
}

// SoftDeleteAvatar mocks base method.
func (m *MockAvatarRepository) SoftDeleteAvatar(ctx context.Context, avatarID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteAvatar", ctx, avatarID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteAvatar indicates an expected call of SoftDeleteAvatar.
func (mr *MockAvatarRepositoryMockRecorder) SoftDeleteAvatar(ctx, avatarID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteAvatar", reflect.TypeOf((*MockAvatarRepository)(nil).SoftDeleteAvatar), ctx, avatarID)
}

// UpdateAvatarStatus mocks base method.
func (m *MockAvatarRepository) UpdateAvatarStatus(ctx context.Context, avatarID, status, thumbnail100S3Key, thumbnail300S3Key string, width, height int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatarStatus", ctx, avatarID, status, thumbnail100S3Key, thumbnail300S3Key, width, height)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatarStatus indicates an expected call of UpdateAvatarStatus.
func (mr *MockAvatarRepositoryMockRecorder) UpdateAvatarStatus(ctx, avatarID, status, thumbnail100S3Key, thumbnail300S3Key, width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatarStatus", reflect.TypeOf((*MockAvatarRepository)(nil).UpdateAvatarStatus), ctx, avatarID, status, thumbnail100S3Key, thumbnail300S3Key, width, height)
}

// MockObjectStorage is a mock of ObjectStorage interface.
type MockObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageMockRecorder
	isgomock struct{}
}

// MockObjectStorageMockRecorder is the mock recorder for MockObjectStorage.
type MockObjectStorageMockRecorder struct {
	mock *MockObjectStorage
}

// NewMockObjectStorage creates a new mock instance.
func NewMockObjectStorage(ctrl *gomock.Controller) *MockObjectStorage {
	mock := &MockObjectStorage{ctrl: ctrl}
	mock.recorder = &MockObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorage) EXPECT() *MockObjectStorageMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockObjectStorage) DeleteObject(ctx context.Context, bucket, objectKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, bucket, objectKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectStorageMockRecorder) DeleteObject(ctx, bucket, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectStorage)(nil).DeleteObject), ctx, bucket, objectKey)
}

// GetObject mocks base method.
func (m *MockObjectStorage) GetObject(ctx context.Context, bucket, objectKey string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, bucket, objectKey)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockObjectStorageMockRecorder) GetObject(ctx, bucket, objectKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockObjectStorage)(nil).GetObject), ctx, bucket, objectKey)
}

// UploadObject mocks base method.
func (m *MockObjectStorage) UploadObject(ctx context.Context, bucket, objectKey string, reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadObject", ctx, bucket, objectKey, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadObject indicates an expected call of UploadObject.
func (mr *MockObjectStorageMockRecorder) UploadObject(ctx, bucket, objectKey, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadObject", reflect.TypeOf((*MockObjectStorage)(nil).UploadObject), ctx, bucket, objectKey, reader)
}

// MockAvatarProducer is a mock of AvatarProducer interface.
type MockAvatarProducer struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarProducerMockRecorder
	isgomock struct{}
}

// MockAvatarProducerMockRecorder is the mock recorder for MockAvatarProducer.
type MockAvatarProducerMockRecorder struct {
	mock *MockAvatarProducer
}

// NewMockAvatarProducer creates a new mock instance.
func NewMockAvatarProducer(ctrl *gomock.Controller) *MockAvatarProducer {
	mock := &MockAvatarProducer{ctrl: ctrl}
	mock.recorder = &MockAvatarProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarProducer) EXPECT() *MockAvatarProducerMockRecorder {
	return m.recorder
}

// PublishAvatarCreatedEvent mocks base method.
func (m *MockAvatarProducer) PublishAvatarCreatedEvent(ctx context.Context, avatarID, userID, s3Key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAvatarCreatedEvent", ctx, avatarID, userID, s3Key)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishAvatarCreatedEvent indicates an expected call of PublishAvatarCreatedEvent.
func (mr *MockAvatarProducerMockRecorder) PublishAvatarCreatedEvent(ctx, avatarID, userID, s3Key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAvatarCreatedEvent", reflect.TypeOf((*MockAvatarProducer)(nil).PublishAvatarCreatedEvent), ctx, avatarID, userID, s3Key)
}
